// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs7NV8bPVSoznwFhXdWwCkL5gU5KkKHnY',
    appId: '1:86907972753:android:c068b45872ff6796c76330',
    messagingSenderId: '86907972753',
    projectId: 'yegna-eqif',
    storageBucket: 'yegna-eqif.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdiwNp0NmfFQnSOZXREo3JUiHcIb2C0BE',
    appId: '1:86907972753:ios:273f4bfc99eb981ec76330',
    messagingSenderId: '86907972753',
    projectId: 'yegna-eqif',
    storageBucket: 'yegna-eqif.firebasestorage.app',
    iosBundleId: 'com.yegnaeqif.yegnaEqifNew',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARwT94k8hHMsencLwn86NySQneKPwYfho',
    appId: '1:86907972753:web:60404510d1f16756c76330',
    messagingSenderId: '86907972753',
    projectId: 'yegna-eqif',
    authDomain: 'yegna-eqif.firebaseapp.com',
    storageBucket: 'yegna-eqif.firebasestorage.app',
  );

}